\cleardoublepage 

# (APPENDIX) Appendix {-}

# Raw Table Excerpts {#raw-table-excerpts}

This appendix contains excerpts of the raw data tables discussed in section \@ref(autoseg)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fs)
library(stringr)
library(magrittr)
library(glue)
library(here)
library(gt)
source("analysis/utils.R")

data_dir <- fs::path(here::here(), "external_data", "Autoseg2012B")

read_excerpt <- function(tbl, data_dir, n_max = 10) {
  get_num_cols <- function(file) {
    readLines(file, n = 1) %>% str_split(";") %>% unlist() %>% length()
  }
  file_path <- paste0(file.path(data_dir, tbl), ".csv")
  ncol_casco_comp <- get_num_cols(file_path)
  read_autoseg(
    file_path,
    n_max = n_max, col_types = paste0(rep("c", ncol_casco_comp), collapse = "")
  )
}

print_table <- function(tbl, tbl_name = NULL) {
  tbl_name <- if (is.null(tbl_name)) 
    as.character(substitute(tbl))
  else tbl_name
  
  tbl %>% 
    gt::gt() %>% 
    gt::tab_header(gt::md(glue::glue("**{tbl_name}**")))
}
```

## Main Tables

Excerpts of the main tables are provided below.

```{r arq_casco_comp, echo = FALSE, fig.cap=""}
arq_casco_comp <- read_excerpt(
  tbl = "arq_casco_comp", data_dir = data_dir
)
print_table(arq_casco_comp)
```

```{r, echo = FALSE}
arq_casco3_comp <- read_excerpt(
  tbl = "arq_casco3_comp", data_dir = data_dir
)
print_table(arq_casco3_comp)
```

```{r, echo = FALSE}
arq_casco4_comp <- read_excerpt(
  tbl = "arq_casco4_comp", data_dir = data_dir
)
print_table(arq_casco4_comp)
```

```{r, echo = FALSE}
premreg <- read_excerpt(
  tbl = "PremReg", data_dir = data_dir
)
print_table(premreg)
```

```{r, echo = FALSE}
sinreg <- read_excerpt(
  tbl = "SinReg", data_dir = data_dir
)
print_table(sinreg)
```

## Auxiliary tables

Excerpts of auxiliary tables are provided below.

```{r, echo = FALSE, include = FALSE}
auto_cat <- read_autoseg(path(data_dir, "auto_cat.csv"))
auto_cau <- read_autoseg(path(data_dir, "auto_cau.csv"))
auto_cep <- read_autoseg(path(data_dir,"auto_cep.csv"))
auto_cidade <- read_autoseg(path(data_dir,"auto_cidade.csv"))
auto_cob <- read_autoseg(path(data_dir,"auto_cob.csv"))
auto_idade <- read_autoseg(path(data_dir,"auto_idade.csv"))
auto_reg <- read_autoseg(path(data_dir,"auto_reg.csv"))
auto_sexo <- read_autoseg(path(data_dir,"auto_sexo.csv"))
auto2_grupo <- read_autoseg(path(data_dir,"auto2_grupo.csv"))
auto2_vei <- read_autoseg(path(data_dir,"auto2_vei.csv"))
```

```{r, echo = FALSE}
print_table(auto_cat)
```

```{r, echo = FALSE}
print_table(auto_cau)
```

```{r, echo = FALSE}
auto_cep %>%
  head(10) %>%
  print_table("auto_cep")
```

```{r, echo = FALSE}
auto_cidade %>%
  head(10) %>%
  print_table("auto_cidade")
```

```{r, echo = FALSE}
print_table(auto_cob)
```

```{r, echo = FALSE}
auto_idade %>%
  head(10) %>%
  print_table("auto_idade")
```

```{r, echo = FALSE}
auto_reg %>%
  head(10) %>%
  print_table("auto_reg")
```

```{r, echo = FALSE}
print_table(auto_sexo)
```

```{r, echo = FALSE}
auto2_grupo %>%
  head(10) %>%
  print_table("auto2_grupo")
```

```{r, echo = FALSE}
auto2_vei %>%
  head(10) %>%
  print_table("auto2_vei")
```