--- 
title: "Practical Ratemaking"
author: "Authors"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: kasaai/pc-pricing-tutorial
description: "Practical guide to P&C ratemaking."
---

# Preface {-}

Advances in machine learning and open source technologies are having a profound impact on many industries, and insurance is no exception. In the US, both the Society of Actuaries and CAS Institute list knowledge of R as a requirement in exam syllabi [@soapa; @cspaexam]. In a draft white paper on regulatory review of predictive models, the National Association of Insurance Commisioners (NAIC) recognizes that actuaries are using techniques such as random forests and neural networks in predictive modeling projects [@naicwhitepaper]. However, while much has been written on modeling methodology for pricing, there have been few resources that include reproducible code. To the best of our knowledge, prior to the current book, no tutorials exist that show the end-to-end pricing workflow.

In this book, we discuss various aspects of property & casualty (also known as general or nonlife) insurance pricing by going over an example project in detail, from preparing raw data for modeling to filing. Throughout the process, we provide reproducible code for each analysis task so the reader can follow along. We also discuss adherence to current regulatory guidelines, so actuaries can better adopt the workflow presented in their work.

In addition to practicing actuaries, the target audience of this book includes actuarial students and data scientists, who either work in insurance already or are looking to transition to the industry. There are no formal prerequisites to the book and we will refer readers to relevant resources as we go along. However, it would be helpful if the reader has knowledge or experience in one of statistical modeling, R programming, or insurance generally.