---
title: "[DRAFT] Personal Auto Pricing"
description: |
  A tutorial for P&C pricing using R.
author:
  - name: Author
    affiliation: Affiliation
  - name: Author
    affiliation: Affiliation
date: "`r Sys.Date()`"
output: 
    radix::radix_article:
      self_contained: false
      toc: true
      toc_depth: 1
bibliography: ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Advances in machine learning and open source technologies are having a profound impact on many industries, and insurance is no exception. In the US, both the Society of Actuaries and CAS Institute list knowledge of R as a requirement in exam syllabi [@soapa; @cspaexam]. In a draft white paper on regulatory review of predictive models, the National Association of Insurance Commisioners (NAIC) recognizes that actuaries are using techniques such as random forests and neural networks in predictive modeling projects [@naicwhitepaper]. However, while much has been written on modeling methodology for pricing, there have been few freely available resources that include reproducible code; one such example is [@alfredo]. To the best of our knowledge, prior to the current article, no tutorials exist that show the end-to-end pricing workflow.

In this tutorial, we walk through an example of a pricing project using R, from preparing raw data for modeling to filing. Throughout the process, we provide reproducible code for each analysis task so the reader can follow along. We also attempt to adhere to the latest regulatory guidelines, so actuaries can better adopt the workflow presented in their work.

# Data

In this tutorial, we use the publicly available data from Brazil's Superintendence of Private Insurance (SUSEP). It maintains policy-characteristics-level data for personal auto from 2007 to 2014 for all insured vehicles in Brazil. This data source was chosen because it contains a variety of variables, from policyholder characteristics to losses by peril, to support a nontrivial analysis, and contains a variety of mapping tables so we can demonstrate a broader range of data manipulation work found in a typical pricing assignment. You can access the data from SUSEP's [AUTOSEG](http://www2.susep.gov.br/menuestatistica/Autoseg/principal.aspx) website.

**(Talk about using 2013 data and validation scheme, see [issues/41](https://github.com/kasaai/pc-pricing-tutorial/issues/41))**

## Data details

With the help of documentation accompanying the datasets, we compile a list of tables shown below.

#### Main Tables

**(consider collapsing)**

**(these need to be in better English see [issues/42](https://github.com/kasaai/pc-pricing-tutorial/issues/42))**

| File      | Description                                                          |
|-----------|----------------------------------------------------------------------|
| arq_casco | Exposure data, premiums, claims and insured amount for the CASCO overhead, classified by the Key Category Rate / Region / Model / Year / Sex / Age Range |
| arq_casco3| Exposure data, premiums and claims for the CASCO overhang, classified by the Key Rate Category / CEP / Model / Year key |
|arq_casco4 | Exposure data, premiums and claims for the CASCO overhang, classified by the Key Rate Category / City / Model / Year |
| premreg   | Regional distribution of prices |
| sinreg    | Regional distribution of claims |

#### Auxiliary Tables

| File        | Description                                                          |
|-------------|----------------------------------------------------------------------|
| auto2_vei   | FIPE code and description of each vehicle model, in addition to the group code to which it belongs |
| auto2_group | Code and description of model groups it contains                     |
| auto_cat    | Description code of tariff categories                                |
| auto_cau    | Code and description of causes of accidents                          |
| auto_cep    | Correlates the CEP with cities and regions of circulation            |
| auto_cob    | Code and description of covers                                       |
| auto_idade  | Code and description of age groups                                   |
| auto_reg    | Code and description of regions of circulation                       |
| auto_sexo   | Code and description of sex (male, female, legal)                    |
| auto_city   | Code and name of cities                                              |

The excerpts for each of the source tables, before any transformations, can be found at [Raw Table Excerpts](https://github.com/kasaai/pc-pricing-tutorial/blob/master/analysis/raw-table-excerpts.md).

We note that, for the purpose of this exercise, we'll use the `arq_casco` policy table since it is the only one that contains poilcyholder characteristics (sex and age.) We are unable to utilize `arq_casco3` and `arq_casco4`, which contain more granular location information, since there are no keys to join by; presumably the data is presented this way to preserve privacy.

## Data prep

Because the source data is in Portuguese, the first order of business is to obtain translations of the column names so we can all understand them. **TODO: dictionary**

**(Maybe include column translation code here)**

**(Look at data summaries for reasonableness, note this is before formal "EDA")**

We observe that, with the exception of the numeric columns, all of the columns contain coded values which need to be mapped. By referencing the data documentation, we create the data model diagram below **TODO: actually do this**.

**(Maybe include data joining snippet here, see [issues/49](https://github.com/kasaai/pc-pricing-tutorial/issues/49) and [issues/44](https://github.com/kasaai/pc-pricing-tutorial/issues/44))**

**(Inspect combined table for reasonableness and reconcile with summaries of mapping tables.)**

# EDA

Distributions
"One-way" analysis

# Modeling

Variable selection, modeling, etc.

# Rating plan

Transfer results to plan, dislocation analysis, etc.



